export const GET_BREED_LIST_REQUEST = 'GET_BREED_LIST_REQUEST';
export const GET_BREED_LIST_SUCCESS = 'GET_BREED_LIST_SUCCESS';
export const GET_BREED_LIST_FAILURE = 'GET_BREED_LIST_FAILURE';
export const GET_BREED_RANDOM_IMAGE_REQUEST = 'GET_BREED_RANDOM_IMAGE_REQUEST';
export const GET_BREED_RANDOM_IMAGE_SUCCESS = 'GET_BREED_RANDOM_IMAGE_SUCCESS';
export const GET_BREED_RANDOM_IMAGE_FAILURE = 'GET_BREED_RANDOM_IMAGE_FAILURE';

export const GET_BREED_LIST_URL = 'https://dog.ceo/api/breeds/list/all';
export const GET_BREED_URL = 'https://dog.ceo/api/breed/breedPartUrl/images/random';
